name: lepaya_app
description: Trainers List
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

  flutter_hooks: ^0.15.0
  get_it: ^7.2.0
  retrofit: ^2.2.0
  floor: ^1.2.0
  flutter_bloc: ^6.1.1
  equatable: ^1.2.5
  ionicons: ^0.0.3
  ffi: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^2.2.0
  floor_generator: ^1.2.0
  build_runner: ^2.1.7
  lint: ^1.0.0
  mockito: ^5.0.17

flutter:
  uses-material-design: true
  fonts:
    - family: Butler
      fonts:
        - asset: assets/fonts/Butler_Bold.ttf
        - asset: assets/fonts/Butler_Light.ttf
        - asset: assets/fonts/Butler_Regular.ttf

    - family: IBM
      fonts:
        - asset: assets/fonts/IBMPlexSans-Bold.ttf
        - asset: assets/fonts/IBMPlexSans-Light.ttf
        - asset: assets/fonts/IBMPlexSans-Regular.ttf
